# Generated by Django 3.1.6 on 2021-02-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210214_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.CharField(max_length=120)),
                ('name', models.ManyToManyField(to='blog.Order')),
            ],
        ),
    ]
